### ISSUE TITLE
Paperclip is deprecated

### ISSUE THREAD

**Issue by harsh183** [fuseumass/dashboard#243] opened 2020-06-23 15:52 UTC
Rails has it's own built in [ActiveStorage](https://guides.rubyonrails.org/active_storage_overview.html).

Their own page says 

> Paperclip is deprecated.
> For new projects, we recommend Rails' own ActiveStorage.
> For existing projects, please consult and contribute to the migration guide, available in [English](https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md), en español, and as a video recorded at RailsConf 2019.
> Alternatively, for existing projects, Kreeti is maintaining [kt-paperclip](https://github.com/kreeti/kt-paperclip), an ongoing fork of Paperclip.

**Comment by ikhatri** [comment] 2020-06-23 17:29
Duplicate of #58

**Closed by ikhatri** 2020-06-23 17:29 UTC
